# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from PyQt5.QtWidgets import QMessageBox



class Ui_SignupWindow(object):
    def show_missmatch(self):
        msg = QMessageBox()
        msg.setWindowTitle("Error")
        msg.setText("password and confirmpass are not same")
        msg.setIcon(QMessageBox.Warning)
        msg.exec_()
    def show_confirm(self):
        msg = QMessageBox()
        msg.setWindowTitle("Welcome")
        msg.setText("SignUp Successful")
        msg.setIcon(QMessageBox.Information)
        msg.exec_()
    def show_notconfirm(self):
        msg = QMessageBox()
        msg.setWindowTitle("Error")
        msg.setText("Email already exist !")
        msg.setIcon(QMessageBox.Critical)
        msg.exec_()
    def show_emptyfill(self):
        msg = QMessageBox()
        msg.setWindowTitle("Error")
        msg.setText("Please fill info !")
        msg.setIcon(QMessageBox.Warning)
        msg.exec_()

    def database_signup(self):
        try:
            txt_name=self.name.text()
            txt_emailid=self.email_2.text()
            txt_password=self.password_2.text()
            txt_confirmpass=self.confirmpass.text()
            txt_fav1=self.email_3.text()
            txt_fav2=self.email_6.text()

            conn=sqlite3.connect('userinfo.db')
            cursor = conn.cursor()
            if txt_password == txt_confirmpass:
                if (txt_fav1 != '' and txt_fav2 != '' and txt_name != '' and txt_emailid != '' and txt_password != '' and txt_confirmpass != ''):
                    cursor.execute(" INSERT INTO user(name,emailid,password,favourite1,favourite2)VALUES(?,?,?,?,?)",(txt_name, txt_emailid,txt_password,txt_fav1,txt_fav2))
                    conn.commit()
                    # cursor.close()
                    # conn.close()
                    self.show_confirm()
                    self.name.setText('')
                    self.email_2.setText('')
                    self.password_2.setText('')
                    self.confirmpass.setText('')
                    self.email_3.setText('')
                    self.email_6.setText('')
                    self.gotologin()

                else:
                    self.show_emptyfill()
            else:
                self.show_missmatch()
        except:
            self.show_notconfirm()
            conn.rollback()
        finally:
            if conn is not None:
                conn.close()


    def gotologin(self):
        from login import Ui_LoginWindow
        self.window = QtWidgets.QDialog()
        self.ui = Ui_LoginWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, SignupWindow):
        SignupWindow.setObjectName("SignupWindow")
        SignupWindow.resize(711, 897)
        SignupWindow.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.Login = QtWidgets.QLabel(SignupWindow)
        self.Login.setGeometry(QtCore.QRect(270, 30, 201, 71))
        self.Login.setStyleSheet("color: rgb(225, 225, 225);\n"
"font: 28pt \"Helvetica\";")
        self.Login.setObjectName("Login")
        self.email = QtWidgets.QLabel(SignupWindow)
        self.email.setGeometry(QtCore.QRect(40, 250, 71, 41))
        self.email.setStyleSheet("font: 15pt \"Verdana\";\n"
"color: rgb(255, 0, 255);")
        self.email.setObjectName("email")
        self.email_2 = QtWidgets.QLineEdit(SignupWindow)
        self.email_2.setGeometry(QtCore.QRect(230, 240, 381, 51))
        self.email_2.setStyleSheet("font: 12pt \"Verdana\";\n"
"color: rgb(240, 240, 240);")
        self.email_2.setText("")
        self.email_2.setObjectName("email_2")
        self.password = QtWidgets.QLabel(SignupWindow)
        self.password.setGeometry(QtCore.QRect(40, 340, 121, 61))
        self.password.setStyleSheet("font: 15pt \"Verdana\";\n"
"color: rgb(255, 0, 255);")
        self.password.setObjectName("password")
        self.password_2 = QtWidgets.QLineEdit(SignupWindow)
        self.password_2.setGeometry(QtCore.QRect(230, 340, 381, 51))
        self.password_2.setStyleSheet("font: 12pt \"Verdana\";\n"
"color: rgb(240, 240, 240);")
        self.password_2.setText("")
        self.password_2.setObjectName("password_2")
        self.signupbutton = QtWidgets.QPushButton(SignupWindow)
        self.signupbutton.setGeometry(QtCore.QRect(470, 820, 151, 51))
        self.signupbutton.setStyleSheet("color: rgb(244, 244, 244);\n"
"background-color: rgb(153, 153, 153);\n"
"font: 14pt \"Verdana\";")
        self.signupbutton.setObjectName("signupbutton")
        self.confirmpass = QtWidgets.QLineEdit(SignupWindow)
        self.signupbutton.clicked.connect(self.database_signup)
        self.confirmpass.setGeometry(QtCore.QRect(230, 440, 381, 51))
        self.confirmpass.setStyleSheet("font: 12pt \"Verdana\";\n"
"color: rgb(240, 240, 240);")
        self.confirmpass.setText("")
        self.confirmpass.setObjectName("confirmpass")
        self.password_4 = QtWidgets.QLabel(SignupWindow)
        self.password_4.setGeometry(QtCore.QRect(40, 440, 161, 61))
        self.password_4.setStyleSheet("font: 15pt \"Verdana\";\n"
"color: rgb(255, 0, 255);")
        self.password_4.setObjectName("password_4")
        self.name = QtWidgets.QLineEdit(SignupWindow)
        self.name.setGeometry(QtCore.QRect(230, 140, 381, 51))
        self.name.setStyleSheet("font: 12pt \"Verdana\";\n"
"color: rgb(240, 240, 240);")
        self.name.setText("")
        self.name.setObjectName("name")
        self.email_4 = QtWidgets.QLabel(SignupWindow)
        self.email_4.setGeometry(QtCore.QRect(40, 150, 81, 41))
        self.email_4.setStyleSheet("font: 15pt \"Verdana\";\n"
"color: rgb(255, 0, 255);")
        self.email_4.setObjectName("email_4")
        self.signupback = QtWidgets.QPushButton(SignupWindow)
        self.signupback.setGeometry(QtCore.QRect(40, 820, 151, 51))
        self.signupback.setStyleSheet("color: rgb(244, 244, 244);\n"
"background-color: rgb(153, 153, 153);\n"
"font: 14pt \"Verdana\";")
        self.signupback.setObjectName("signupback")
        self.email_5 = QtWidgets.QLabel(SignupWindow)
        self.signupback.clicked.connect(self.gotologin)
        self.signupback.clicked.connect(SignupWindow.close)
        self.email_5.setGeometry(QtCore.QRect(40, 650, 81, 41))
        self.email_5.setStyleSheet("font: 15pt \"Verdana\";\n"
"color: rgb(255, 0, 255);")
        self.email_5.setObjectName("email_5")
        self.email_3 = QtWidgets.QLineEdit(SignupWindow)
        self.email_3.setGeometry(QtCore.QRect(230, 650, 391, 51))
        self.email_3.setStyleSheet("font: 12pt \"Verdana\";\n"
"color: rgb(240, 240, 240);")
        self.email_3.setText("")
        self.email_3.setObjectName("email_3")
        self.email_6 = QtWidgets.QLineEdit(SignupWindow)
        self.email_6.setGeometry(QtCore.QRect(230, 740, 391, 51))
        self.email_6.setStyleSheet("font: 12pt \"Verdana\";\n"
"color: rgb(240, 240, 240);")
        self.email_6.setText("")
        self.email_6.setObjectName("email_6")
        self.email_7 = QtWidgets.QLabel(SignupWindow)
        self.email_7.setGeometry(QtCore.QRect(40, 750, 81, 41))
        self.email_7.setStyleSheet("font: 15pt \"Verdana\";\n"
"color: rgb(255, 0, 255);")
        self.email_7.setObjectName("email_7")
        self.email_8 = QtWidgets.QLabel(SignupWindow)
        self.email_8.setGeometry(QtCore.QRect(220, 590, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.email_8.setFont(font)
        self.email_8.setStyleSheet("font: 10pt \"Verdana\";\n"
"color: rgb(255, 0, 0);\n"
"")
        self.email_8.setObjectName("email_8")
        self.email_9 = QtWidgets.QLabel(SignupWindow)
        self.email_9.setGeometry(QtCore.QRect(40, 530, 381, 41))
        self.email_9.setStyleSheet("font: 15pt \"Verdana\";\n"
"color: rgb(255, 0, 255);")
        self.email_9.setObjectName("email_9")

        self.retranslateUi(SignupWindow)
        QtCore.QMetaObject.connectSlotsByName(SignupWindow)

    def retranslateUi(self, SignupWindow):
        _translate = QtCore.QCoreApplication.translate
        SignupWindow.setWindowTitle(_translate("SignupWindow", "Dialog"))
        self.Login.setText(_translate("SignupWindow", "Sign Up"))
        self.email.setText(_translate("SignupWindow", "Email"))
        self.password.setText(_translate("SignupWindow", "Password"))
        self.signupbutton.setText(_translate("SignupWindow", "SIGN UP"))
        self.password_4.setText(_translate("SignupWindow", "Confirm Pass"))
        self.email_4.setText(_translate("SignupWindow", "Name"))
        self.signupback.setText(_translate("SignupWindow", "BACK"))
        self.email_5.setText(_translate("SignupWindow", "Fav. 1"))
        self.email_7.setText(_translate("SignupWindow", "Fav. 2"))
        self.email_8.setText(_translate("SignupWindow", "Eg - www.google.com"))
        self.email_9.setText(_translate("SignupWindow", "Enter your favourite Websites"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignupWindow = QtWidgets.QDialog()
    ui = Ui_SignupWindow()
    ui.setupUi(SignupWindow)
    SignupWindow.show()
    sys.exit(app.exec_())
